### ISSUE TITLE
Where to update list of plugins?

### ISSUE THREAD

**Issue by sagold** [bayleeadamoss/zazu#104]
Hey there.

Thanks for the nice API. Custom plugins seem to be really simple. I tested this on a dictionary https://github.com/sagold/zazu-dict and was wondering if you are interested in listing available plugins on your page?

If that is the case, any guidance would be welcome.

Regards

**Comment by bayleedev** [comment]
@sagold I'd love a dictionary plugin listed on the website.

They are currently on the site here:
http://zazuapp.org/plugins/

You can create a file here:
https://github.com/tinytacoteam/zazu/tree/master/docs/_packages

Submit a pr and I'll merge it :D

**Comment by sagold** [comment]
@blainesch. Thanks for the feedback. I would suggest to add those points to `docs/creating plugins`.

**Comment by bayleedev** [comment]
Great idea [:

**Comment by bayleedev** [comment]
I added this to the documentation. Thanks!
