### ISSUE TITLE
Zazu not building on Windows 8.1, 64bit

### ISSUE THREAD

**Issue by silverspectro** [bayleeadamoss/zazu#105]
steps to reproduce : 
- git clone zazu
- npm install

-> error on husky package installation

+ The windows build seems to install fine, but i can't see the Zazu window showing.
I see the app icon in the taskbar, but no window nor activities when i type or press Enter.

Material :

OS : Windows 8.1
Processor : Intel core i5 4460s
RAM : 16go
64bit

**Comment by bayleedev** [comment]
Can you paste the npm-debug.log in a gist and link it here? I'll try and download a VM soon to see if I can't reproduce it.

**Comment by schmic** [comment]
@silverspectro I had that "issue" yesterday as well on Win10 and it fell back to missing "git" in my path.

I checked out via Babun-Shell and tried to build with cmd-Shell.

**Comment by bayleedev** [comment]
You shouldn't need git in your path, it should fallback to downloading zip files from github. I'm currently rewriting the package installer in zazu now, there should be a better version in the next release.

**Comment by bayleedev** [comment]
@silverspectro can you try this again with v0.3.2?

**Comment by bayleedev** [comment]
It's been a few weeks without a response, I'm closing this, but if the problem persists please open it again. Thanks!
