### ISSUE TITLE
Mac tray icon is scaled improperly

### ISSUE THREAD

**Issue by jredwards** [bayleeadamoss/zazu#109]
Not actually sure if it's a scaling issue or an issue with the png itself, but it looks wrong.

![](https://i.imgur.com/8cnAPZ2.png)

**Comment by bayleedev** [comment]
Yes, it's wrong. I didn't measure correctly. I'd love to have this fixed. Thank you for reporting! [:

**Comment by bayleedev** [comment]
This will be fixed with c44ab9a0e96aad78b40781ba54d8237cb519b5b8 during the next release.

**Comment by bayleedev** [comment]
@jredwards zazu v0.3.2 has a better icon for mac now.
