### ISSUE TITLE
Plugins aren't working after install

### ISSUE THREAD

**Issue by rafi** [bayleeadamoss/zazu#111]
I'm seeing these errors in log after a fresh install on macOS 10.12.2
```
{"query":"chrom","plugin":"tinytacoteam/zazu-system","block":"input","level":"verbose","message":"Executing Script","timestamp":"2017-01-05T20:02:42.818Z"}
{"plugin":"tinytacoteam/zazu-file-finder","block":"FindApp","level":"info","message":"Script Results","timestamp":"2017-01-05T20:02:42.821Z"}
{"plugin":"tinytacoteam/zazu-file-finder","block":"FindApp","level":"error","message":"results must be an array","timestamp":"2017-01-05T20:02:42.823Z"}
{"results":[],"plugin":"tinytacoteam/zazu-system","block":"input","level":"info","message":"Script Results","timestamp":"2017-01-05T20:02:42.825Z"}
{"level":"info","message":"Updating query to \"chrome\"","timestamp":"2017-01-05T20:02:42.875Z"}
{"message":"Plugin failed to load","stack":["Error: Cannot find module 'typed-function'","    at Module._resolveFilename (module.js:455:15)","    at Function.Module._resolveFilename (/Applications/Zazu.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)","    at Function.Module._load (module.js:403:25)","    at Module.require (module.js:483:17)","    at require (internal/module.js:20:19)","    at Object.<anonymous> (/Users/rafi/.zazu/plugins/tinytacoteam/zazu-calculator/node_modules/mathjs/lib/core/typed.js:1:100)","    at Module._compile (module.js:556:32)","    at Object.Module._extensions..js (module.js:565:10)","    at Module.load (module.js:473:32)","    at tryModuleLoad (module.js:432:12)"],"plugin":"tinytacoteam/zazu-calculator","block":"Service","level":"error","timestamp":"2017-01-05T20:02:42.875Z"}
```

**Comment by bayleedev** [comment]
The first error `results must be an array` is normal when the file-finder isn't done being initialized.

The second looks like the plugin dependencies failed to install. Can you try and run `npm install` inside of `/Users/rafi/.zazu/plugins/tinytacoteam/zazu-calculator` ?

**Comment by sagold** [comment]
- This seems to be related to #102
- I can reproduce this on my machine (since today/strange)
- looking into my plugins folder some modules are installed, but others are missing (a diff exists)
- reinstalling fetches all dependencies but will probably not work since a node-version mismatch

*Manually reinstalling (a single) plugin's node_modules*

1. `npm i`
2. `npm i electron-rebuild`
3. `./node_modules/.bin/electron-rebuild --version 1.3.1`

**Comment by rafi** [comment]
@blainesch I've tried, `npm install` in that directory doesn't output anything, and re-running zazu the dependency error is still happening.

**Comment by bayleedev** [comment]
@rafi I believe v0.3.2 of zazu should address this, can you reinstall and let me know?

**Comment by rafi** [comment]
@blainesch so far so good, thanks! :)
