### ISSUE TITLE
Zazu not displaying on Windows 7

### ISSUE THREAD

**Issue by hill4575** [bayleeadamoss/zazu#114]
No search box ever opens on Windows 7 system. 
Seeing the following in the logs no search windows opens.

{"level":"info","message":"triggered zazu hotkey"}
{"level":"verbose","message":"sending showWindow event from toggle event"}

**Comment by bayleedev** [comment]
Is git installed on your box locally?

**Comment by hill4575** [comment]
No it wasn't. It is now. And I should have been more clear. Zazu was installed from the zazu-v0.2.3-win32-ia32.exe release package.

**Comment by ghost** [comment]
I'm having the same issue on Windows 10

**Comment by whudwl** [comment]
same here. When I use "toggle zazu" menu I only see a tiny tiny input box on screen, and a tiny tiny scroll bar far away from it to the right.  I used zazu-v0.2.3-win32-ia32.exe on windows 10. tried to run it as admin too.

**Comment by hachesilva** [comment]
Same here.

This info might be useful:
Windows 8.1
Two monitors via displaylink
Custom desktop using Stardock Fences

**Comment by CalJacobson** [comment]
I've also encountered this, with Win 7 (Enterprise) SP1, three monitors (to include laptop in docking station).  Git 2.8.0 is installed.

**Comment by indadev** [comment]
I used zazu-v0.2.3-win32-ia32.exe and i have the same problem. My windows is 64 and there is only one win instalator for 32.

**Comment by alejandroaguilera** [comment]
Installed zazu-v0.2.3-win32-ia32 on a Windows 7 Profesional machine 64 bit. Alt+space is not showing anything. Tried to change the hotkey but it's still not showing.

**Comment by ConcurrentHashMap** [comment]
Can confirm the same under Windows 7 Pro 64bit. The shortcut as well as "Toggle Zazu" does only hide the focus of the current window, but does not display anything.

**Comment by iki** [comment]
+1 on Win8/x64 with zazu-v0.2.3-win32-ia32.exe installed, it shows `Your plugins have been loaded` and then nothing happens on Alt+space, or Toggle Zazu from systray icon menu.

Btw, where are the logs? I didn't find them in `<Profile>\AppData\Roaming\Zazu` or `C:\Program Files (x86)\Zazu`.

Also, Alt+space isn't a good shortcut for Windows, it overrides default keayboard switcher key.

**Comment by alejandroaguilera** [comment]
@iki For me logs are on `C:\Users\<youruser>\.zazu`

**Comment by bayleedev** [comment]
I have a pre-release for this issue. After I do some more testing I'll publish it for updates.

**Comment by bayleedev** [comment]
@hill4575 the latest version v0.3.2 should address this, can you try again?

**Comment by hill4575** [comment]
It is working for me, thank you!

**Comment by bayleedev** [comment]
Thank you!

**Comment by alejandroaguilera** [comment]
Working for me too! Thanks!

**Comment by bayleedev** [comment]
w00t!

**Comment by ghost** [comment]
Works for me now but I had to:
mkdir %HOMEPATH%\.zazu\plugins\tinytacoteam

On Tue, Jan 10, 2017 at 5:29 AM, Blaine Schmeisser <notifications@github.com
