### ISSUE TITLE
Reload Config deletes custom plugins

### ISSUE THREAD

**Issue by phbo85** [bayleeadamoss/zazu#120]
### Versions
* Zazu: 0.2.3
* OS: Windows 10

I'm trying to create a plugin. But every time when zazu updates the config, the plugin folder get's deleted and the standard plugins are getting downloaded again. The new plugin I created however is gone.

**Comment by bayleedev** [comment]
`Reload Config` should just restart Zazu, do you mean `Update plugins` ?

**Comment by phbo85** [comment]
I'm sorry, you are right. 

Is this how it is expected to work?

**Comment by bayleedev** [comment]
What version of git do you have installed?

It should only delete the directory if it's:
1. inside of your `~/.zazurc.json` file
2. the local version doesn't match the remote version
3. you don't have git installed

When we "clone" a repo without git we add a file inside the folder with the current "sha" of the project. We then compare this sha to the repo version of the repo.

My guess is that you don't have git installed, you put the plugin inside of your config file, and the remote repo does not exist. 

https://github.com/tinytacoteam/zazu/blob/6cdfca2467df9c3e403b4c6fe52bc2760d5d3ce9/app/lib/github.js#L31-L32

During this equality check, one must be `null` and the other `undefined`, it deletes your folder. Then we have a 😢

**Comment by bayleedev** [comment]
@phbo85 if you have an idea on how to make this experience better, I'd love to hear it.
