### ISSUE TITLE
Zazu claims .zazurc.json is invalid if it is a symlink

### ISSUE THREAD

**Issue by bw-yuhogg** [bayleeadamoss/zazu#121]
### Expected Behavior

Zazu should operate properly if .zazurc.json is a symlink to a valid JSON file.

### Actual Behavior

Zazu refuses to open if .zazurc.json is a symlink zazurc.json.real. It opens a popup with the following text:

```
You have an invalid ~/.zazurc.json file.
Please edit your ~/.zazurc.json file and try loading Zazu again.
```

### Steps to reproduce the behavior

1. Rename a valid .zazurc.json to zazurc.json.real
2. Create a symlink named .zazurc.json pointing to zazurc.json.real
3. Launch Zazu.app

### Versions

* Zazu: 0.2.3
* OS: macOS El Capitan 10.11.6
* GIT (if you have it installed): git version 2.11.0

Please, include a link to gist of most applicable `~/.zazu/log/` file. See https://gist.github.com/rwhogg/264a44a24e582dc9cffd6d86bf166083

**Comment by bayleedev** [comment]
Thank you for reporting this, this is a critical issue.

**Comment by bayleedev** [comment]
If you're original file doesn't have a `.json` extension this doesn't load it correctly. Can the back up file also include `.json` at the end?

This is a limitation of node's `require()` statement.

**Comment by bw-yuhogg** [comment]
No, the file extension is very particular. However, you can work around this issue with two levels of symlinks: .zazurc.json -> zazurc.json.real -> zazurc.json

Sorry, didn't occur to me that `require` was particular about that when following symlinks.

**Comment by bayleedev** [comment]
That's a clever workaround! I'm glad you found a way to make it work, thanks for letting us know. [:
