### ISSUE TITLE
Reveal Config in Finder

### ISSUE THREAD

**Issue by jlarmstrongiv** [bayleeadamoss/zazu#122]
It'd be nice to have a "reveal in finder" option for the configuration files when clicking on the application icon in the menu bar on a mac (for zazurc.js, zazu.json, ~/.zazurc.json, etc.)  Just a thought.

**Comment by bayleedev** [comment]
I'm planning on making a plugin for managing configuration, and this would fit perfectly with that.

**Comment by bayleedev** [comment]
This is fixed in the new package manager: tinytacoteam/zazu-package-manager@84e42b0b8dcc0281fd9648187f8d145d313b4010
