### ISSUE TITLE
Zazu Icon Too Big on macOS Menu Bar

### ISSUE THREAD

**Issue by TGNYC** [bayleeadamoss/zazu#127]
### Expected Behavior

Consistent with macOS [Icon Guidelines](https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/OSXHIGuidelines/IconsGraphics.html#//apple_ref/doc/uid/20000957-CH14-SW1) and [Menu Guidelines](https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/OSXHIGuidelines/MenuBarMenus.html) and generally look good.

### Actual Behavior

Icon is huge and intersects with the top and bottom of menu bar

![screen shot 2017-01-08 at 12 59 41 pm](https://cloud.githubusercontent.com/assets/18518375/21752213/638a2bae-d5a2-11e6-9d96-37c79e141894.png)

### Steps to reproduce the behavior

Install on macOS

### Versions

* Zazu: 0.2.3
* OS: macOS Sierra 10.12.2

**Comment by bayleedev** [comment]
This is a duplicate of #109 and has been fixed in master and will go out with the next release.
