### ISSUE TITLE
npm install via Update Plugins Menu not install all dependencies

### ISSUE THREAD

**Issue by nantaphop** [bayleeadamoss/zazu#130]
### Expected Behavior
I develop new plugin which have to install `node-notifier` when I Update Plugins zazu should install all my plugin dependencies

### Actual Behavior
In my case only `/node_modules/node-notifier` were found. No dependencies of `node-notifier` found

### Steps to reproduce the behavior
- run `npm install node-notifier --save` maybe in zazu-template
- delete folder `node_modules`
- Click menu Update Plugins in Zazu menu
- `node_modules` now have only `node_notifier` directory. All its dependencies were gone.

### Versions

* Zazu: 0.23
* OS: OSX Sierra 10.12.2

**Comment by bayleedev** [comment]
Thank you for reporting this!

**Comment by bayleedev** [comment]
Can you try this out on `v0.3.2` and see if this still persists?

**Comment by nantaphop** [comment]
@blainesch already try it still persists in 0.3.2 :(

**Comment by bayleedev** [comment]
I'll take a deeper look, thank you!

**Comment by nantaphop** [comment]
@blainesch For some mystery reason it working now. Is it possible that some time zazu run `npm install` with difference option?

**Comment by bayleedev** [comment]
No, it always runs it the same way, but zazu 0.3.2 has some retry logic to make it run more than once if it fails.

**Comment by bayleedev** [comment]
My guess is that `node-notifier` is a native module and zazu must be having a hard time installing that.

**Comment by nantaphop** [comment]
I think so, node-notifier install script tell me it prefer install as global. So, sometime install script work fine sometime not.

Do you have any suggestion about how to zazu notify user for some information that should sent to user after they pressed enter button.

I currently working on zazu-docker-plugin which let user stop/start or list running docker instance. So, I would like to notify user when type enter “docker start mysql” “docker stop mysql” or “docker ps” something   like that.

Thank!

**Comment by bayleedev** [comment]
@nantaphop You can configure our plugin to send notifications without the `node-notifier` via zazu blocks:

http://zazuapp.org/documentation/blocks/#send-notification

**Comment by nantaphop** [comment]
Thank a lot, I will look at that.
