### ISSUE TITLE
Don't beep after pressing Enter

### ISSUE THREAD

**Issue by rbeeger** [bayleeadamoss/zazu#137]
### Expected Behavior
After selecting an item from the list and pressing Enter no sound is emitted by the app 
### Actual Behavior
After selecting an item from the list and pressing Enter the computer beeps
### Steps to reproduce the behavior
Open Zazu, enter something, move the cursor to the desired item, press Enter
### Versions

* Zazu: 0.3.2
* OS: macOS Sierra 10.12.2
* GIT (if you have it installed): 2.11.0

Please, include a link to gist of most applicable `~/.zazu/log/` file.

**Comment by rbeeger** [comment]
It also beeps when dismissing Zazu by pressing ESC directly after opening it.

**Comment by bayleedev** [comment]
Duplicate of #96
