### ISSUE TITLE
More plugins

### ISSUE THREAD

**Issue by brpaz** [bayleeadamoss/zazu#140]
Hello.
After tried [Hain](https://github.com/appetizermonster/hain), [Dext](https://github.com/vutran/dext), now I have discovered zazu and I am loving it.

I really like Alfred but I work mostly on Linux so I am really looking to a decent alternative.
Still, here is a long way to go to make zazu as usefull, since Alfted have a workflow for anything!
It would be nice to gather some people to work on plugins. I have some ideas and I will try to make my first plugin in the weekend, but I have like a list of 30+ plugins I would like to do.

Any plans for more plugins soon or anyone interested in working on that?

Keep up the great work with this. I hope I finally found my launcher of choice in Linux.

**Comment by blakek** [comment]
Hey @brpaz! I've made a few ideas I've started on myself.  I'd be interested in creating more, too!

**Comment by bayleedev** [comment]
I'd love to make more plugins. Maybe you should list them out to inspire some devs?

**Comment by brpaz** [comment]
@blainesch Yes I agree. May be we can use this issue to keep track of that?

We have to find a way to build a bigger community around zazu and having more people to contribute with plugins. I missed a tool like this in Linux for a long time. I am sure I am not the only one.

Here some ideas of plugins that I would like to have in zazu (I will start working on the first ones next weekend):

- Base64 encoder / decoder plugin - Already build this for Dext, will do it again for zazu.
- Ip Plugin - Displays information about current ip address
- Strong password generator plugin - Ex: https://github.com/rasshofer/alfred-password-generator-workflow
- [CanIuse plugin ](caniuse.com) - similar to [this](https://github.com/willfarrell/alfred-caniuse-workflow) alfred workflow
- Package Mangers plugins (npm, packagist, docker hub, etc). - Ex: https://github.com/peterjmit/alfred-packagist
- DevDocs / documentation search plugin - Ex: https://github.com/yannickglt/alfred-devdocs
- Timezone plugin
- Processes plugin - https://www.alfredforum.com/topic/1077-top-processes-based-memory-or-cpu-usage-workflow/
- Trello plugin - Ex: https://github.com/MikoMagni/Alfred-for-Trello
- SSH Plugin - Ex: https://github.com/isometry/alfred-ssh
- Weather plugin - Ex https://www.alfredforum.com/topic/193-weather-workflow-with-conditions-and-forecast/
- Shorten Url plugin - http://www.packal.org/workflow/shorten-url

**Comment by bayleedev** [comment]
A few of those would be really simple to make! This should be fun

**Comment by blakek** [comment]
@brpaz I've already got an [IP plugin](https://github.com/blakek/zazu-ip-address), just have to add it to the plugins list 😄 

I agree, several of those should be very simple, quick, and fun to make

**Comment by bayleedev** [comment]
@brpaz I just submitted my weather plugin!

https://github.com/blainesch/zazu-weather

**Comment by bayleedev** [comment]
@brpaz I haven't submitted it yet, but I made a tinyurl plugin!

https://github.com/blainesch/zazu-tinyurl

**Comment by eldinoyev** [comment]
@blainesch dang you beat me to it

**Comment by eldinoyev** [comment]
Maybe we can come up with a board to track which contributors are working on which plugins?

**Comment by bayleedev** [comment]
@eldinoyev sorry I'll let others contribute [:

If you wanna reserve it, you can create a PR to add it to the plugin directory. I'll wait until it's done to merge it.

**Comment by brpaz** [comment]
Awesome!! I will work on the base64 encoder/decoder plugin next weekend.

**Comment by bayleedev** [comment]
@brpaz Instead of just base64, maybe it could support a few encoding/decodings similar to the alfred one?

https://github.com/willfarrell/alfred-encode-decode-workflow

**Comment by eldinoyev** [comment]
@blainesch Nah no worries, I'll jump on another plugin or find an issue. Yours is certainly far ahead of mine

**Comment by bayleedev** [comment]
@eldinoyev if you want to pair on one I'm up for that as well! :D

**Comment by eldinoyev** [comment]
@blainesch That's an awesome idea! Think we're going to come up with a trello board or something down the road to manage this kind of stuff? or do you prefer issue tracker for the most part?

**Comment by bayleedev** [comment]
No idea honestly. Issues seem the best idea so far, since a new person could join without needing an approval process.

**Comment by brpaz** [comment]
@eldinoyev @blainesch A trello board would be nice, but if we want to keep it simpler, maybe we can use Github issues with a specific label and then using, the "Projects" feature to have a "trello like" board?

btw, found [this](https://github.com/zenorocha/alfred-workflows) nice list of Alfred workflows to have some more ideas

**Comment by bayleedev** [comment]
@brpaz feel free to create an issue here and I can label it for you. I wouldn't want to add friction to new developers by requiring them to ask permission.

If you want to standardize that we can add it to the readme or in the plugin page on the website.

**Comment by eldinoyev** [comment]
@brpaz @blainesch Totally forgot about the Projects feature. Yeah I agree about Trello creating friction for new developers. Maybe something as simple as a short contribution guide that includes directions on claiming 'ownership' over an issue so that a maintainer can make them an Assignee (if that is something you want to do, Blaine) and other useful info. 

Just an idea though.

**Comment by bayleedev** [comment]
I'm okay with that. If you want to create a pr with those instructions somewhere that would be awesome :D

**Comment by bayleedev** [comment]
A lot of these plugins have been made. If we need a specific plugin that blocks your workflow we should make issues for individual plugins, and I'm sure the community or myself would be happy to help create them.

Thanks for the list, @brpaz!
