### ISSUE TITLE
Clicking "Update Plugins" on Windows 10 replaces all Zazu files.

### ISSUE THREAD

**Issue by cecoates** [bayleeadamoss/zazu#141]
### Expected Behavior
Click update plugins. Zazu scans plugins again, picking up new changes.

### Actual Behavior
Click update plugins. Zazu does update the plugins, but in the process re-installs all plugin data and overwrites all files with the defaults. Including any changes you've made to files such as directories.js.

### Steps to reproduce the behavior
Click update plugins. Wait for Zazu to update. Check the .zazu directory. All files have been replaced.

### Versions

* Zazu: 3.2
* OS: Windows 10
* GIT (if you have it installed):

Please, include a link to gist of most applicable `~/.zazu/log/` file.

[zazu.log.2017-01-10.txt](https://github.com/tinytacoteam/zazu/files/697687/zazu.log.2017-01-10.txt)

**Comment by bayleedev** [comment]
What version of git do you have installed?

**Comment by cecoates** [comment]
Ah. I guess that's the newbie in me showing. I did not think to install git separately in Windows.

I installed 2.11, made sure to choose the cmd option, then reinstalled Zazu, and it seems to have stopped overwriting everything.

**Comment by bayleedev** [comment]
actually you shouldn't need git, but if you have git installed it'll use it.

Without git installed it'll download the zip's from github. The logic that checks to see if it needs to re-download it must be broken. I'll try and do some tests on windows.

**Comment by schmic** [comment]
Fact is that files will be overwritten as well when the zip-file is extracted.
Configuration shouldn't be mixed with source code.
a) it breaks stuff on updates
b) its not practical for a normal user to fiddle inside some .js-file

How about some default configuration delivered with the plugin which can be overwritten/extended from inside the .zazurc.json? The zazu-fallback-plugin uses that for the list of rootSearches already.

**Comment by bayleedev** [comment]
@schmic valid point. Even if it's your own plugin, you can push to a feature branch.
