### ISSUE TITLE
UI displays across two monitors in Ubuntu

### ISSUE THREAD

**Issue by charlesmilam** [bayleeadamoss/zazu#142]
### Expected Behavior
UI opens in the center of the screen of primary monitor **Optional:** UI opens in center of screen upon whichever monitor the mouse is on #124 . **Optional:** UI can be 'dragged' to a location on the screen and will remain sticky to that location whenever opened. **Optional:** Coordinates can be added to config file for location of UI on the desktop.

### Actual Behavior
UI opens centered across two monitors. Half on the primary monitor, half on the secondary monitor.

### Steps to reproduce the behavior
- Add second monitor
- Set in Settings > Display > Secondary Display (join this display with another to create an extra workspace)
- Bring up UI using hotkeys

### Versions

* Zazu: 0.3.2
* OS: Ubuntu 16.04 (fully updated) using Budgie Desktop

### Additional Notes
Have added the variable 'onMouse' from #129 to my config file (set to true), but this has not changed the behavior.

**Comment by charlesmilam** [comment]
Got smart, and actually tried dragging the UI around. By clicking on the feather in the UI, I am able to drag the UI to a location of my choosing on either monitor, and it remains sticky to that location on subsequent openings.

Is this an undocumented feature, or did I miss it in the documentation somewhere. I would not have known to even try this had it not been for some experience with Alfred.

Still feel proper default behavior would be to open centered on the primary monitor.

**Comment by bayleedev** [comment]
This seems related to #92

It is undocumented, I'm not exactly sure where to put it. Where would you expect to see that documented at?

**Comment by schmic** [comment]
@CharlesMilam I would say that you don't have a primary monitor cause you joined both together.

Electron opens centered by default which isn't overwritten by Zazu and which happens in your situation. The [screen](https://github.com/electron/electron/blob/master/docs/api/screen.md) module does have some helpers like getPrimaryScreen() and getAllDisplays() but I don't have an idea when to calculate the location and not display it centered.

**Comment by brpaz** [comment]
Havent looked at how zazu handles browser windows but something like this might help: https://github.com/BoostIO/Boostnote/pull/102/files

**Comment by charlesmilam** [comment]
@blainesch Perhaps the easiest place to put it would be as an additional question in the FAQ, along the lines of 'Can the UI be repositioned?'.  Another consideration would be on the 'Getting Started' page, with a new section for 'Additional Notes' or 'Tips' which contains things like the positioning feature and any other notes/tips that might be helpful to new users (although no others currently come to mind). I do like the rather minimal instructions, and given that the intended audience is 'hackers, creators and dabblers', I don't feel too much hand holding is required (I was quite pleased with myself for 'finding' the positioning feature). All that being said, it is a nice feature that should be documented. Had the UI initially opened centered on my primary monitor, and I had known of the feature, I would have immediately moved it, as I like it centered in the upper half of my screen.

@schmic I understand what you are saying about not having a true 'primary monitor', and really just an extended desktop. But that is what Ubuntu offers to me, at least through the Settings>Display applet. And they are listed as Primary and Secondary. I don't readily see any option for tying a monitor to a particular workspace. This might just be an Ubuntu thing, as on my work laptop (Mac Book Pro), I have two external monitors attached, and did not experience this issue. Since the UI does get centered, does Electron see my resolution as being something like 3840x1280? Is that even a common resolution on ultra-wide single monitors? Perhaps a kludgey work around would be if a wonky resolution is detected, then some kind of offset is provided that would place the UI entirely on one of the monitors. Have no idea if this is even possible.

**Comment by schmic** [comment]
@CharlesMilam I guess the resolution from Screen.getPrimaryDisplay() will be 3840x1280 in your case, yes.
I'll try to package a little demo application for you that verifies that and I will test the on Windows as well, where you can merge two monitors into one with the nvidia driver as well.

**Comment by schmic** [comment]
@CharlesMilam I attached [electron-multi-display.zip](https://github.com/tinytacoteam/zazu/files/701737/electron-multi-display.zip) here. Could you please download it and run `npm install` and `npm start` and paste your output?

On my workstation here I have three separate displays (Win10)
```
==== DISPLAY LIST:
Display 0 { id: 2528732444,
  bounds: { x: 0, y: 0, width: 1680, height: 1050 },
  workArea: { x: 0, y: 0, width: 1680, height: 1020 },
  size: { width: 1680, height: 1050 },
  workAreaSize: { width: 1680, height: 1020 },
  scaleFactor: 1,
  rotation: 0,
  touchSupport: 'unknown' }
Display 1 { id: 2779098405,
  bounds: { x: 1680, y: 0, width: 1680, height: 1050 },
  workArea: { x: 1680, y: 0, width: 1680, height: 1020 },
  size: { width: 1680, height: 1050 },
  workAreaSize: { width: 1680, height: 1020 },
  scaleFactor: 1,
  rotation: 0,
  touchSupport: 'unknown' }
Display 2 { id: 2841568472,
  bounds: { x: -1920, y: 0, width: 1920, height: 1080 },
  workArea: { x: -1920, y: 0, width: 1920, height: 1050 },
  size: { width: 1920, height: 1080 },
  workAreaSize: { width: 1920, height: 1050 },
  scaleFactor: 1,
  rotation: 0,
  touchSupport: 'unknown' }



==== PRIMARY DISPLAY:
Primary { id: 2528732444,
  bounds: { x: 0, y: 0, width: 1680, height: 1050 },
  workArea: { x: 0, y: 0, width: 1680, height: 1020 },
  size: { width: 1680, height: 1050 },
  workAreaSize: { width: 1680, height: 1020 },
  scaleFactor: 1,
  rotation: 0,
  touchSupport: 'unknown' }
```

**Comment by charlesmilam** [comment]
@schmic as requested:

```
==== DISPLAY LIST:
Display 0 { id: 1881264395124736,
  bounds: { x: 0, y: 0, width: 1920, height: 1080 },
  workArea: { x: 0, y: 34, width: 1920, height: 1046 },
  size: { width: 1920, height: 1080 },
  workAreaSize: { width: 1920, height: 1046 },
  scaleFactor: 1,
  rotation: 0,
  touchSupport: 'unknown' }
Display 1 { id: 1251256766510340,
  bounds: { x: 1920, y: 0, width: 1920, height: 1080 },
  workArea: { x: 1920, y: 34, width: 1920, height: 1046 },
  size: { width: 1920, height: 1080 },
  workAreaSize: { width: 1920, height: 1046 },
  scaleFactor: 1,
  rotation: 0,
  touchSupport: 'unknown' }



==== PRIMARY DISPLAY:
Primary { id: 1881264395124736,
  bounds: { x: 0, y: 0, width: 1920, height: 1080 },
  workArea: { x: 0, y: 34, width: 1920, height: 1046 },
  size: { width: 1920, height: 1080 },
  workAreaSize: { width: 1920, height: 1046 },
  scaleFactor: 1,
  rotation: 0,
  touchSupport: 'unknown' }

```

**Comment by schmic** [comment]
Alright, thanks @CharlesMilam 

I'll implement a fix for that problem.
My solution would be:
- by default Zazu opens centered on primary dsiplay
- configuration option to display on screen the mouse pointer currently is, also centered

**Comment by bayleedev** [comment]
@schmic I believe that might be happening in #160 by @eldinoyev

it is nice to know this will fix this issue though :D

**Comment by charlesmilam** [comment]
@schmic Glad to help, and your solution seems an appropriate default.

Question: could the configuration option, to display on the screen the mouse pointer is currently on, take into account custom placement of the UI via dragging, just place it in that custom location for the current screen?

**Comment by charlesmilam** [comment]
Sorry for the late response.

Zazu now centers itself properly on my Ubuntu 16.04 install when using multiple monitors.

Thanks for the work on this, it now makes Zazu that much more enjoyable to use.

**Comment by bayleedev** [comment]
Thanks @CharlesMilam !!
