### ISSUE TITLE
Replace electron-prebuilt with electron as dependency

### ISSUE THREAD

**Issue by schmic** [bayleeadamoss/zazu#143]
### Expected Behavior
Use the (newly) available electron package in package.json as dependency

### Actual Behavior
The obsolete electron-prebuilt package is used.

### Steps to reproduce the behavior
See this [blog entry](http://electron.atom.io/blog/2016/08/16/npm-install-electron).

**Comment by bayleedev** [comment]
I also saw this email. When we decide to upgrade electron, we'll switch to not using prebuilt.

**Comment by schmic** [comment]
The currently used version 1.3.1 is also available from that new repository, dunno if they will drop that old repository.

**Comment by bayleedev** [comment]
This was done in v0.4.0 of zazu.
