### ISSUE TITLE
Zazu request update after uninstall

### ISSUE THREAD

**Issue by jgossett** [bayleeadamoss/zazu#145]
### Expected Behavior
The updater should uninstall with the application.

### Actual Behavior
4 days ago I uninstalled Zazu. Yesterday, Zazu requested me to download or ignore a update. 

### Versions

* Zazu: 0.3.2
* OS: Windows 7
* GIT: N?A

### Log file.
[zazu.log.2017-01-11.txt](https://github.com/tinytacoteam/zazu/files/699325/zazu.log.2017-01-11.txt)

**Comment by bayleedev** [comment]
Can you close zazu and try uninstalling it again? I don't think it completed.

**Comment by jgossett** [comment]
Blaine,

I did install, close and uninstall. When I look at the msconfig , Zazu
still has a start up task. Did you want a screenshot?

Josh

**Comment by bayleedev** [comment]
@jgossett that implies the uninstaller left the startup task and the app itself?

I'm currently in the process of switching the way we build apps, so this could be fixed when that comes out.

**Comment by jgossett** [comment]
Blaine,

Sound good. If you need me to test, please let me know.

Josh

Joshua Gossett
-------------------------------------------------------------
127 Cleveland Avenue South
Saint Paul, Minnesota 55105
Telephone (651) 434-3873
Email joshua.gossett@gmail.com

On Wed, Jan 11, 2017 at 2:56 PM, Blaine Schmeisser <notifications@github.com

**Comment by bayleedev** [comment]
We have a new packager, which means a new installer. Do you mind trying with v0.4.0?

**Comment by jgossett** [comment]
Blaine,

Tried it out. Worked well. Kudos.

Have you guys experimented with text to speech. I am interested in this
project but I would like to better understand the challenges.

Jsoh


On Feb 10, 2017 12:38 PM, "Blaine Schmeisser" <notifications@github.com>
wrote:

We have a new packager, which means a new installer. Do you mind trying
with v0.4.0?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tinytacoteam/zazu/issues/145#issuecomment-279028144>,
or mute the thread

**Comment by bayleedev** [comment]
I believe Lacona does natural language things, so voice might be a better extension for that. Siri on Mac's also do voice activation.

Glad it helped!
