### ISSUE TITLE
How can I check my current zazu version?

### ISSUE THREAD

**Issue by caiquecastro** [bayleeadamoss/zazu#146]
Is there a way to check which zazu version I am currently using?

**Comment by bayleedev** [comment]
Totally. Click on the zazu icon in the doc, then click "about zazu"

<img width="234" alt="screenshot_1_11_17__9_07_am" src="https://cloud.githubusercontent.com/assets/769039/21858290/65a85054-d7dd-11e6-84f9-6076e3b16f5f.png">
<img width="432" alt="how_can_i_check_my_current_zazu_version__ _issue__146_ _tinytacoteam_zazu" src="https://cloud.githubusercontent.com/assets/769039/21858312/78ec3450-d7dd-11e6-87dd-e8ea70fcf3c9.png">
