### ISSUE TITLE
Fallback searches are dominating the results

### ISSUE THREAD

**Issue by amjith** [bayleeadamoss/zazu#147]
### Expected Behavior

I'd like to see the fall back search results to be the last items in the results.

### Actual Behavior

The fall back search results are usually listed on the top of the results.

### Steps to reproduce the behavior

* Add a few fall-back searches to `~/.zazurc.json`
* Add the vpn plugin to `~/.zazurc.json`

```
    "amjith/zazu-mac-vpn",
    {
      "name": "tinytacoteam/zazu-fallback",
      "variables": {
        "rootSearches": [
          "google",
          "wolf",
          "mdn",
          "gh"
        ]
      }
    }
```

* Try `,v abc`, notice how the results from the vpn plugin are at the bottom below the fallback search.

### Versions

* Zazu: 0.3.2
* OS: OS X

Please, include a link to gist of most applicable `~/.zazu/log/` file.

https://gist.github.com/amjith/51c0d7c65c1b6fc3dd7d5943bff5d8da

**Comment by bayleedev** [comment]
So the way this works is Zazu initial gives priority to plugins that respond faster. So if two new plugins are installed and they both respond to the same input, the one that responds first will be at the top.

For instance the calculator plugin responds faster than the fallback search, but the fallback search responds faster than the vpn plugin:

![calculator](https://cloud.githubusercontent.com/assets/769039/21870015/3127c206-d80f-11e6-8f16-168708c952bb.png)
![vpn](https://cloud.githubusercontent.com/assets/769039/21870022/34e12e1e-d80f-11e6-8831-75e4aff1a2e5.png)

If you click on a result the `id` of that result gets bumped up so it's closer to the top for that query.

I can think of two solutions:

1) Make your vpn plugin faster! It's getting the list of vpn's on the fly. These could be cached. Currently the horrible way I made the fallback search respond slower is that it contains a [setTimout](https://github.com/tinytacoteam/zazu-fallback/blob/master/root.js#L18-L24).

2) Zazu could allow plugins to define their own priority somehow. But this would need to be fair, and Zazu would still need to be able to bump results that are clicked on more.

https://github.com/tinytacoteam/zazu/blob/master/app/containers/pluginWrapper.js#L148-L163

https://github.com/tinytacoteam/zazu/blob/master/app/transforms/resultSorter.js

**Comment by blakek** [comment]
What if, instead of giving plugins the power to determine priority, the results were ordered based on the order they were listed in `~/.zazurc.json`?  I guess it _could_ be weird if you were scrolling down the list of results, and a plugin that made a network request returned a second later.  However, I think we could manage that UX somehow.

Another thing I thought of was giving PrefixScript and Keyword blocks higher priority, but I'm not sure if that would be fair to scripts accepting a wider range of input (e.g. the calculator would be lower in the results).

**Comment by bayleedev** [comment]
I like the idea of prioritizing block types. I'd probably pick this order:

* Prefix
* Keyword
* Root

We could sub-rank based on load time, then have Zazu do it's own sort later on if you click on the result.

What do you think?

**Comment by amjith** [comment]
Yes. Having a set ranking based on the plugin type and using the load time as a secondary sort is a good idea.

**Comment by Koolstr** [comment]
This has been bothering me as well. I like the proposed solution; please implement it.

**Comment by bayleedev** [comment]
This will go out in the next release.
