### ISSUE TITLE
Idea: Don't activate Zazu plugins or start searching until there's a delay in typing.

### ISSUE THREAD

**Issue by cecoates** [bayleeadamoss/zazu#150]
I noticed when reviewing the logs trying to see if I messed anything up while I'm testing that Zazu seems to activate every plugin with every keystroke.

So if I'm trying to open chrome, for example, the log will be full of results where each plugins is running with:

"for c"
"for ch"
"for chr" 

And so on. 

Similarly, if you want to open a file, typing "open" will result in every plugin doing searches like:

"for o"
"for op"
"for ope"

Which results in a bit of lag, because it even pulls up executables with "ope" in it.

Would it make any difference if Zazu didn't immediately start searching, or you could control the delay somehow in the json? Then you'd only be running one search for "chrome" or one search for "open resume".

Example of what I mean:

I tried some searches. First I type out a search/command normally. Like "chrome" or "open bills".

Then I close Zazu, re-open it, and paste a pre-copied result of the same search. Bam! It's pretty fast. 

http://cld.wthms.co/B6RC

**Comment by bayleedev** [comment]
It's a great idea, but it has some technical issues. There was a previously created ticket for this #125
