### ISSUE TITLE
Installation on ARM Jessie

### ISSUE THREAD

**Issue by neolao** [bayleeadamoss/zazu#152]
I tried to install the application in a fresh install of Jessie on Raspberry Pi. 

```
> robotjs@0.4.5 install /home/pi/workspace/zazu/node_modules/robotjs
> prebuild --install

prebuild WARN install No prebuilt binaries found (target=v7.4.0 arch=arm platform=linux)
```

But it works if the requirements of RobotJS are installed: https://github.com/octalmage/robotjs#building

I don't know if you can do something about that.

**Comment by bayleedev** [comment]
If you just run `npm install robotjs` does it work?

**Comment by neolao** [comment]
No

**Comment by bayleedev** [comment]
I believe travis runs the builds on a debian based CI server. There are some dependencies it should install, but maybe a few need to be manually installed?

There is a ticket on robotjs covering these dependencies.

https://github.com/octalmage/robotjs/issues/17
