### ISSUE TITLE
Most plugins don't work on default macOS install

### ISSUE THREAD

**Issue by 2shortplanks** [bayleeadamoss/zazu#157]
### Expected Behavior

Typing "13 feet to inches" does the conversion

### Actual Behavior

Displays the fallbacks

<img width="713" alt="screenshot 2017-01-12 19 30 07" src="https://cloud.githubusercontent.com/assets/46818/21914172/5e289686-d8ff-11e6-9d09-8c1726775894.png">

### Steps to reproduce the behavior

1. Go to http://zazuapp.org/download/, download 0.3.2 for Mac OS X, install
2. Launch Zazu, wait for plugins loaded notification
3. Hit alt-space
4. Type "13 feet to inches

### Versions

* Zazu: 0.3.2
* OS: macOS 10.12.2
* GIT: ???

Please, include a link to gist of most applicable `~/.zazu/log/` file.
https://gist.github.com/2shortplanks/32aa0894593d84499fb01833293b7846

**Comment by 2shortplanks** [comment]
The first time I ran Zazu I double clicked it from the dmg.  Could this have screwed up installing plugins?

**Comment by bayleedev** [comment]
The log is interesting, one line says it completed installing the dependencies of the calculator, and another said it's missing one.

Do you mind trying to `rm -rf ~/.zazu` and launching it not from the dmg? I don't think it should matter honestly, but maybe there is some funky behavior? I'll try and reproduce, I'm also on a Mac.

**Comment by 2shortplanks** [comment]
I deleted .zaru and it worked as it should.

I couldn't replicate this issue by deleting .zazu again and double clicking on the zazu.app in the DMG.  (I even tried deleting the zazu.app out of /Applications, and still couldn't replicate this.). Most odd

**Comment by bayleedev** [comment]
Odd indeed. I'd like to reproduce this, it seems like it's happened before. Thanks for making the gist, it'll be good reference if somebody else finds it in the wild.
