### ISSUE TITLE
Zazu uses too much CPU on idle mode

### ISSUE THREAD

**Issue by avaly** [bayleeadamoss/zazu#189]
### Expected Behavior

On idle mode, the zazu processes should not consume any CPU.

### Actual Behavior

On idle mode, 2 of the 4 processes opened by zazu are using 5-25% CPU.

![selection_2017-01-31_1194x119](https://cloud.githubusercontent.com/assets/356100/22485810/f76ee5ee-e7fe-11e6-8efa-a68d6bdc024f.png)

### Steps to reproduce the behavior

Do not invoke/toggle zazu, run `top` and find its processes.

### Versions

* Zazu: 0.3.2
* OS: Ubuntu 16.04

**Comment by bayleedev** [comment]
@avaly can you try removing the plugin `tinytacoteam/zazu-file-finder` and see if the problem persists?

**Comment by avaly** [comment]
I removed the `file-finder` plugin from my config file, but it had no effect on the CPU usage.

**Comment by bayleedev** [comment]
My guess is that one of the plugins is causing this, so it might be worth deleting them until you find out which one is causing it. If you delete them all and the problem persists, it's zazu core. Do you mind checking?

**Comment by avaly** [comment]
Removing all my plugins from the config does bring down the CPU usage, but not to 0. Now it's fluctuating between 0.5%-5%. So it's definitely a core issue as well.

**Comment by bayleedev** [comment]
Were there any specific plugins boosting it another 20%?

What cpu does Chrome run at on your computer?

**Comment by avaly** [comment]
Chrome with an empty tab consumes between 0%-0.3% CPU, but mostly 0%.

I added my plugins back in the config one by one, and the one that made the CPU jump (+10%) than the others was `tinytacoteam/zazu-clipboard`.

**Comment by bayleedev** [comment]
The clipboard does have a service that checks the clipboard [every second](https://github.com/tinytacoteam/zazu-clipboard/blob/master/zazu.json#L13), it could possibly check less frequently 5-10 seconds, but frequent copies may not get registered.

**Comment by twang2218** [comment]
I can confirm the high CPU usage on `zazu-clipboard` on Linux. 
By default, `zazu` have `10%` CPU usage:

```bash
$ ps aux | grep zazu
taowang   4423 12.2  1.4 1391412 118256 ?      Sl   13:02   4:50 /opt/Zazu/zazu
```

After remove the `zazu-clipboard`, it's down to about `1%`:

```bash
$ ps aux | grep zazu
taowang   7134  1.2  1.3 1371528 106828 ?      Sl   13:45   0:01 /opt/Zazu/zazu
```

**Comment by twang2218** [comment]
Submitted a PR https://github.com/tinytacoteam/zazu-clipboard/issues/16, which increase the interval, I think 3 seconds might long enough to reduce the CPU usage.

**Comment by twang2218** [comment]
@avaly Could you try to increase the interval to see whether it will solve your problem or not?

Edit the `~/.zazu/plugins/tinytacoteam/zazu-clipboard/zazu.json` file, with the following changes:

```diff
        "type": "ServiceScript",
-        "script": "src/monitor.js"
+        "script": "src/monitor.js",
+        "interval": 3000
       },
```

Then restart zazu to see whether CPU usage has been reduced or not. Thanks.

**Comment by avaly** [comment]
@twang2218 It does have the effect of CPU going down indeed after I changed the interval to 3000.

**Comment by twang2218** [comment]
@avaly Thank you.

@blainesch Just check the code, I think the default interval is 0.1 seconds, which cause pretty high cpu usage, https://github.com/tinytacoteam/zazu/blob/master/app/blocks/external/serviceScript.js#L14:

```js
    this.interval = parseInt(data.interval, 10)
    if (isNaN(this.interval) || this.interval < 100) {
      this.interval = 100
    }
```

Should we change the default to `1000` for 1 second here?

**Comment by bayleedev** [comment]
I should also mention I made a commit (without a pr, sorry!) that should have helped the performance:

https://github.com/tinytacoteam/zazu-clipboard/commit/52056c3f8afc8a23df31fb1e87473263c9706d35

**Comment by harryio** [comment]
same issue
