### ISSUE TITLE
Plugins loading window stuck when no plugins configured

### ISSUE THREAD

**Issue by avaly** [bayleeadamoss/zazu#190]
### Expected Behavior

The "plugins loading" window should not show up.

### Actual Behavior

The "plugins loading" window shows up and does not disappear until it loses focus.

![selection_2017-02-01_684x250](https://cloud.githubusercontent.com/assets/356100/22516626/441bb0e4-e89e-11e6-8870-dc7c3109cf8b.png)

### Steps to reproduce the behavior

- Remove all plugins from your config file
- Toggle Zazu

### Versions

* Zazu: 0.3.2
* OS: Ubuntu 16.04

**Comment by bayleedev** [comment]
Do we feel this screen gives enough information to debug why zazu isn't working? ie add more plugins?

**Comment by eldinoyev** [comment]
Without plugins, it's pretty much just an input field. Maybe some kind of default window that says Zazu needs plugins to work, and links to or shows the plugins list.

**Comment by bayleedev** [comment]
The link would make it more actionable, great idea.

**Comment by bayleedev** [comment]
This will go out in the next release.
