### ISSUE TITLE
Zazu isn't functioning (only calculator and web search works)

### ISSUE THREAD

**Issue by arieljannai** [bayleeadamoss/zazu#194]
### Expected Behavior
Plugins will and app will work?

### Actual Behavior
The only plugin that seems to work is the calculator, which show me results whenever I start typing numbers.
find/open doesn't seem to have any affect, nor the emoji plugin.

### Steps to reproduce the behavior
I just installed it and tried to use it.

### Versions

* Zazu: 0.3.2
* OS: Windows 10, 1607
* GIT: 2.11

Please, include a link to gist of most applicable `~/.zazu/log/` file.
https://gist.github.com/arieljannai/7a641a016fbb65f18007d2429294f6d3

Maybe I need to use another node version? (currently installed 6.5.0)

What I tried (which didn't helped):
* Running Zazu as administrator.
* Reorder the plugins.
* Remove the fallback, since it always arrives to it.

Thanks!

**Comment by bayleedev** [comment]
It looks like you've gotten results from `zazu-emoj` too, correct?

If so, the main thing that isn't working is the file finder. What does the directory `~/.zazu/plugins/tinytacoteam/zazu-file-finder/data` look like? If it contains an `applications.json` file can you post the contents in a gist?

**Comment by arieljannai** [comment]
Hi, thanks.
@blainesch 

* The folder is empty (except the `.gitkeep`).
* Actually `emoj` also didn't worked when I posted it. A bit later I kept trying and playing with the config and somehow `emoj` started showing eventually

**Comment by arieljannai** [comment]
Tried looking into procmon. Zazu is indeed trying to look for `applications.json` but it doesn't exist.

**Comment by bayleedev** [comment]
It must be having an issue saving it. Can you tell me what commit the file finder is currently at?

~~~
cd ~/.zazu/plugins/tinytacoteam/zazu-file-finder
git rev-parse HEAD
~~~

Also, do you have any custom configuration for the file finder or is the default?

**Comment by arieljannai** [comment]
I tried some custom configuration to see if that helps, but it didn't worked with and without extra configuration on the file finder.
It was on tinytacoteam/zazu-file-finder@afc5379124455819de9fceeca1ce33af280c04fb, I tried pulling to see if something changes, and now it's on tinytacoteam/zazu-file-finder@afc40964d7fe7e5cf25bac35e75d739a72151f93 (no affect)

**Comment by twang2218** [comment]
@arieljannai If `~/.zazu/plugins/tinytacoteam/zazu-file-finder/data` is empty except `.gitkeep`, that might be something wrong within the generator, could you try manually run this command and paste the result back here?

```bash
cd ~/.zazu/plugins/tinytacoteam/zazu-file-finder/
node appCache.js '{}'
```

**Comment by arieljannai** [comment]
Found the problem.
`mkdirp` wasn't installed since it was a dev dependency. I created a [PR about it](https://github.com/tinytacoteam/zazu-file-finder/pull/27)

**Comment by arieljannai** [comment]
I installed it manually and then run the above command, and it worked.
I also moved it in the `package.json` to the `dependencies` section and than chose `Update Plugins` from Zazu's context menu, and now it's working (installed dependencies and created `applications.json`)

**Comment by twang2218** [comment]
Fixed by https://github.com/tinytacoteam/zazu-file-finder/issues/27 and merged, closing now.
