### ISSUE TITLE
should auto reload config when installing plugins

### ISSUE THREAD

**Issue by hayes** [bayleeadamoss/zazu#196]
### Expected Behavior
plugin should work after it installs
### Actual Behavior
plugins do not work until config is reloaded
### Steps to reproduce the behavior
install a plugin, try to use plugin
### Versions

* Zazu: latest?
* OS:x
* GIT:yes

Please, include a link to gist of most applicable `~/.zazu/log/` file.

**Comment by bayleedev** [comment]
We could create an output block to `reload configuration`.
