### ISSUE TITLE
Error when starting windows 10

### ISSUE THREAD

**Issue by scheduardo** [bayleeadamoss/zazu#210]
When starting windows I got an error (attached).

### Expected Behavior

The app should start without errors.

### Actual Behavior

Error when starting windows.

### Steps to reproduce the behavior

Start windows.

### Versions

* Zazu: 0.3.2
* OS: Windows 10 64-bit

![image](https://cloud.githubusercontent.com/assets/19599264/22688292/b7dabffc-ed12-11e6-80ec-988dbbc65a85.png)

**Comment by bayleedev** [comment]
It looks like you're starting zazu without internet access and it's trying to check if there is an update available.

**Comment by scheduardo** [comment]
It's possible! My internet is horrible in the last days.
