### ISSUE TITLE
Release related issue

### ISSUE THREAD

**Issue by twang2218** [bayleeadamoss/zazu#215]
### Latest Release

On Github release page, https://github.com/tinytacoteam/zazu/releases, the `Latest release` is `0.3.2-builder`, which should be `0.4.0`

### Filename format

And the filename format has been changed from previous release, from:

```
zazu-v0.3.2-darwin-x64.dmg
zazu-v0.3.2-linux-x64.deb
zazu-v0.3.2-win32-ia32.exe
```

to

```
zazu-0.4.0.dmg
zazu-Setup-0.4.0.exe
zazu_0.4.0_amd64.deb
```

It causes the `homebrew cask` recipe, https://github.com/caskroom/homebrew-cask/blob/811e3d88f245d5bfd99aedcfc93e5a6bc9a582e3/Casks/zazu.rb#L6, download url template failed, which is:

```
url "https://github.com/tinytacoteam/zazu/releases/download/v#{version}/zazu-v#{version}-darwin-x64.dmg"
```

Of course, we can submit a PR to change the template, but my point is that I think we may need a release procedure/script to formalize the tag, filename format. So, it will easier for the downstream project's integration.

### latest.yml

I'm not quite sure about the purpose of `latest.yml`, but the content only contains Windows-related information:

```yml
version: 0.4.0
path: zazu-Setup-0.4.0.exe
sha2: 915c65adc26746c41da15325b6b8e03ed559824f4d74abf41934d71ae603d24c
```

### appcast.xml

And I think we might need an `appcast.xml` or something else for the Auto Update. Currently, it's only promote to user there is an update, and user have to open zazu website and manually download it. It might be great if it can download automatically.

Currently the `homebrew cask` is using this link: https://github.com/tinytacoteam/zazu/releases.atom, but it doesn't contain the download link.

**Comment by bayleedev** [comment]
The new format is the default for electron builder. We could try and keep the naming convention, but I've already started updating places that reference the old convention. Like the website.

The "deployment" workflow is documented, but it was more of just a rough draft, but it is up to date:
https://github.com/tinytacoteam/zazu#deployment

Brew:

We should update the cask recipe.

latest.yml

I'm not sure why this was uploaded but it's not hurting anything I suppose?

appcast.xml

The electron-builder has things for auto updates but we need to start signing the code. I have an apple developer license now, so I just need to setup some environment variables for mac. I have no clue how to sign windows/linux though, maybe we can pair on this?

Once it's signed we should be able to do auto updates with [github releases](https://github.com/jenslind/electron-gh-releases).

**Comment by bayleedev** [comment]
I submitted to cask here: caskroom/homebrew-cask#30005

I have no clue why the v0.4.0 isn't being shown as the "latest release" do you have any idea?

**Comment by bayleedev** [comment]
Okay the cask is updated and the website is up to date. Is there any other issues?

**Comment by twang2218** [comment]
Most issues solved, I'm closing this issue now, and I will create another PR with a release script to standardize the procedure later.
