### ISSUE TITLE
Any "roadmap" ?

### ISSUE THREAD

**Issue by ohardy** [bayleeadamoss/zazu#226]
Hello,

I just discovered this project and I am really interested to contribute to adding new features or fixing issues so I can replace Alfred on my Mac ^^

Any roadmap or wanted features ?

Thanks in advance

**Comment by bayleedev** [comment]
@ohardy are there any features preventing you from switching?

We have a roadmap, but it's currently a github project. I'd love for this to be more visible, do you have any suggestions?

**Comment by mika76** [comment]
You could use checks in issues and milestones like the dotnet project (eg https://github.com/dotnet/corefx/issues/14492).

A changelog would be good too - I just upgraded to 0.4.0 but have no idea why...

**Comment by bayleedev** [comment]
@mika76 I have a changelog in the repo, but what would be a better way to expose that?

**Comment by afaur** [comment]
@blainesch changelog has 0.3.3 not 0.4.0 version info
https://github.com/tinytacoteam/zazu/blob/v0.4.0/changelog.md

**Comment by mika76** [comment]
@blainesch I'd recommend a nice big link on the download page: http://zazuapp.org/download/

**Comment by ohardy** [comment]
@blainesch

It looks slow when I write, I looked at the code and maybe it's because each plugin do a match and can answer ?
The calculator plugin looks strange:
- You write 4, you got the calculator
- You add a +, calculator is gone, for example Alfred shows '...' and it makes more sense, doesn't it ?

I will write some plugins for Zazu like:
- color to handle conversion in CSS, RGB, selector, etc
- ip address
- 1password
- contacts
- iTunes
- terminal
- Caffeinate
- Dash
- Network tools

If you want to make Zazu a real alternative, it needs a real settings view, theme selector/preview etc.

I am not sure that fetching plugins directly from github is really good. Maybe a repository like Atom or NPM one could be better ?

What do you think about all that ?

**Comment by bayleedev** [comment]
@afaur pull requests welcome [:
