### ISSUE TITLE
Screen custom position

### ISSUE THREAD

**Issue by bayleedev** [bayleeadamoss/zazu#246]
### Expected Behavior

No error

### Actual Behavior

<img width="420" alt="blank_skitch_document" src="https://cloud.githubusercontent.com/assets/769039/23234200/2574be10-f906-11e6-985f-a7b61e7c1f64.png">

### Steps to reproduce the behavior

Randomly happening when using it with Bluejeans app

### Versions

* Zazu: 0.4.0
* OS: el capitan
* GIT: 2.9.2

Please, include a link to gist of most applicable `~/.zazu/log/` file.

https://gist.github.com/anonymous/70b6b4dbeade654fc00b769048f9871c

**Comment by eldinoyev** [comment]
This is really strange. I'm unfamiliar with Bluejeans app, but I'll have a chance to look at the code tomorrow.

**Comment by bayleedev** [comment]
@eldinoyev it looks like `getCurrentScreen` is returning undefined. Since `resetScreens` is synchronous, my guess is that we are missing a screen event somewhere.

Possibly call `resetScreens()` inside of `getCurrentScreen()` if it's fast enough. Either way we should add more logging to this file.

Let me know what you dig up :D

**Comment by bayleedev** [comment]
@RonCrocker also reported this to me, suggesting they broke this by switching from 2 external and a closed laptop to open laptop with no externals.
