### ISSUE TITLE
[Plugin] better zazu-devdocs

### ISSUE THREAD

**Issue by brpaz** [bayleeadamoss/zazu#254]
Hello.
Anyone interested in mimic [this](https://github.com/KELiON/cerebro-devdocs). I think the existing [zazu-devdocs](https://github.com/danielbayerlein/zazu-devdocs) is very limited compared to this.
I really love the fact you can search your docs without leaving the app.

@danielbayerlein , what do you think?

I might give a shot to this, if nobody is interested, but I have some simpler plugins in my todo list before.

**Comment by bayleedev** [comment]
Instead of making another plugin, would it be beneficial to pr the current one?

Also, adding a preview pane should be simple enough, but scrolling would be difficult, since Zazu was made so you didn't need your mouse and the cerebro plugin almost requires it. Maybe simple a snippet in the preview pane and the `<enter>` goes to the documentation online?

**Comment by danielbayerlein** [comment]
@brpaz:

I agree with @blainesch. Let's extend [zazu-devdocs](https://github.com/danielbayerlein/zazu-devdocs) instead of creating a new plugin. I'm open to improve this plugin and PR are very welcome.

**Comment by brpaz** [comment]
Yes I agree. I should have open this issue on the plugin repo.

I think at least being able to search directly for methods would be nice even without preview and you go to directly to devdocs on click. I dont know how it works for dash in alfred for example.

I think we can mimic the work done it cererbro. its also nodejs so it should be pretty similar. @danielbayerlein I will open the issue on your plugin to discuss more details.

**Comment by danielbayerlein** [comment]
https://github.com/danielbayerlein/zazu-devdocs/issues/2

**Comment by bayleedev** [comment]
Good move! :D
