### ISSUE TITLE
[Bug] Zazu Plugin Debugger not filtering

### ISSUE THREAD

**Issue by nalexander50** [bayleeadamoss/zazu#270]
I am writing my first plugin for Zazu, but I am having a hard time working with the Plugin Debugger. There is a decent chance that I'm not using it properly, but it seems to be ignoring my filters.

Chiefly, it appears to completely ignore the Plugin filter. It will always show messages for all plugins. This makes it nearly impossible to isolate any debug information for my plugin since the File Finder and Fallback dominate the debugger.

Similarly, the log level filter behaves intuitively. To me, selecting a log level would imply that only messages of that log level will be displayed. In reality, the filter will display messages of the selected log level or lower. This isn't as big of a deal, but it just took some time for me to notice that the filter wasn't just broken.

### Expected Behavior

- Selecting a plugin filter will filter out all other plugins
- Selecting a log level filter will filter out all other levels

### Actual Behavior

- A plugin filter is not respected
- A log level filter is not respected

### Steps to reproduce the behavior

- Open Plugin Debugger
- Try to filter on plugin
- Try to filter on log level

### Versions

* Zazu:
App Environment: production
App Version: 0.4.0
Electron Version: 1.3.13
Node Version: 6.5.0
Chrome Version: 52.0.2743.82

* OS: Windows 10
* GIT: N/A

**Comment by nalexander50** [comment]
Just took a peek at the code for the debugger and it appears that `selectedPlugin` is not being referenced anywhere, so this behavior is really not surprising. I may take a crack at fixing this issue tonight and submitting a PR.

**Comment by bayleedev** [comment]
Thanks for reporting it, a PR would be awesome!
