### ISSUE TITLE
Error message when it starts

### ISSUE THREAD

**Issue by smachave** [bayleeadamoss/zazu#289]
### Expected Behavior
Shouldn't get the error message, but everything else seems to work fine.
### Actual Behavior
I get this error:
[![boge.png](https://s27.postimg.org/cnx2v8rmr/boge.png)](https://postimg.org/image/furmevc2n/)
### Steps to reproduce the behavior
I have added Zazu to startup programs, and I get this error when I start my computer.
### Versions

* Zazu: 0.5.2
* OS: Windows 8.1
* GIT: 2.10.2.windows.1

Please, include a link to gist of most applicable `~/.zazu/log/` file.
[Link](https://gist.github.com/tkshnwesper/b7f4a84fe537db2489529a556b013b2f)

**Comment by bayleedev** [comment]
The image doesn't show up.

Thank you for reporting. [:

**Comment by smachave** [comment]
Sorry, I wasn't aware GitHub did not cache it.

**Comment by bayleedev** [comment]
It looks like it's trying to rename it to the same thing. My guess is that the file doesn't exist. Can you confirm?

**Comment by smachave** [comment]
These are the contents of the database folder:
[![Screenshot_1.png](https://s28.postimg.org/e21dd257x/Screenshot_1.png)](https://postimg.org/image/69apl2z8p/)

**Comment by bayleedev** [comment]
@tkshnwesper I made a pr at #292

**Comment by smachave** [comment]
👍
