### ISSUE TITLE
Increase Number of Search Results?

### ISSUE THREAD

**Issue by Koolstr** [bayleeadamoss/zazu#295]
What can be done to  increase the number of search results visible in Zazu, each time I search? Right now, only 7 results appear. I would like to see more/set my own number, since looking through clipboard history or scrolling through the fallback search engines can be tedious and slow.

Is there a way to do this already, and I simply could not find it anywhere?

**Comment by bayleedev** [comment]
Each plugin determines how many results it wants to show. Is there a specific plugin you want more results from?

**Comment by Koolstr** [comment]
Not really. Any and all results, but particularly the fallback search engines. Are you saying there would be no way for the main program to have an option to override any defaults?

**Comment by bayleedev** [comment]
Correct, this is controlled from individual plugins.

I'd suggest making an issue with the fallback plugin if you'd like to change it's behavior, I'm sure there are a lot of cases it's not accounting for like you mentioned! :D
