### ISSUE TITLE
shortcuts for launch apps?

### ISSUE THREAD

**Issue by jujes** [bayleeadamoss/zazu#296]
Hi, someone know if possible use zazu with keyboard shortcuts for launch apps?

like:
terminal
chrome
.... etc

thanks in advance,

**Comment by bayleedev** [comment]
You could make a plugin to do this. Start with a [hotkey](http://zazuapp.org/documentation/blocks/#hotkey).

The file finder has a unique way of opening up apps cross platform where it goes to a [user script](http://zazuapp.org/documentation/blocks/#user-script) or an [open file](http://zazuapp.org/documentation/blocks/#open-file) based on the operating system.

You can see how it's done here:

https://github.com/tinytacoteam/zazu-file-finder/blob/master/zazu.json#L41-L54
https://github.com/tinytacoteam/zazu-file-finder/blob/master/openApp.js

If you do create a plugin, I'd love to get it into the plugin directory, thanks for stopping by!
