### ISSUE TITLE
Question: clipboard: how do i see more items from clipboard i see only 7 items

### ISSUE THREAD

**Issue by tomer-ben-david** [bayleeadamoss/zazu#310]
### Expected Behavior
Be able to scroll to more items than 7

### Actual Behavior
Only 7 items are presented, no scroll, have to search for older item. (don't always remember what to search sometimes I just want to scroll).

### Steps to reproduce the behavior
ALT-SHIFT-V

### Versions

* Zazu: 0.5.2
* OS: Mac
* GIT:

Please, include a link to gist of most applicable `~/.zazu/log/` file.

**Comment by afaur** [comment]
Some of this should be resolved in the next release thanks to @Koolstr (https://github.com/tinytacoteam/zazu/pull/300#pullrequestreview-114221704)
