### ISSUE TITLE
Question: is it possible to increase the zazu window size? need to see more text

### ISSUE THREAD

**Issue by tomer-ben-david** [bayleeadamoss/zazu#312]
### Expected Behavior
can increase or resize zazoo popup or scroll to the side to see more text

### Actual Behavior
zazu popup limits the view cannot see enough text to decide if to choose

### Versions

* Zazu:
* OS:
* GIT:

Please, include a link to gist of most applicable `~/.zazu/log/` file.

**Comment by afaur** [comment]
Maybe adding a configurable width setting similar to height which was added here: 
https://github.com/tinytacoteam/zazu/pull/300#pullrequestreview-114221704

**Comment by viewstar000** [comment]
I think let the theme author to control the window size may be a better way.

**Comment by bayleedev** [comment]
@viewstar000 width is hardcoded to 600px.. the max height is adjustable by the user and the default is up to 400px. Themes can use as little or as much as they like upto the max.
