### ISSUE TITLE
...

### ISSUE THREAD

**Issue by richardbmx** [bayleeadamoss/zazu#319]
...

**Comment by danielbayerlein** [comment]
Great work! I like it. What do you think @afaur?

**Comment by richardbmx** [comment]
@danielbayerlein Thank you so much that you liked it.

**Comment by afaur** [comment]
I am open to this proposal and have been trying to determine what changes would be required if the community decides to proceed with this.

I propose we create a branch or repo that tracks design files to make this an easier process going forward. It would also be a place where a designer could submit a PR with a proposal on how a logo would look in each placement scenario.

If this proposal is accepted we would need a member to make these changes and submit a PR with the correct modifications in the identified areas. 

Here is an example of some identified areas where branding occurs with a possible suggestion for how the logo might look in that scenario:

- Web favicon
  - Before
  <img width="230" alt="favicon-before" src="https://user-images.githubusercontent.com/898523/39407553-742ffd2a-4b7c-11e8-958b-8e59161d317f.png">

  - After
  <img width="230" alt="favicon-after" src="https://user-images.githubusercontent.com/898523/39407552-741b2774-4b7c-11e8-839f-0b75de8a3f0e.png">

- Regular Tray

  - Before
  <img width="20" alt="regular-tray-before" src="https://user-images.githubusercontent.com/898523/39407559-74b4cf6e-4b7c-11e8-9d03-b766a41356bb.png">

  - After
  <img width="20" alt="regular-tray-after" src="https://user-images.githubusercontent.com/898523/39407558-74a1d13e-4b7c-11e8-8f8e-00694406eaa7.png">

- Inverted Tray
  - Before
  <img width="20" alt="inverted-tray-before" src="https://user-images.githubusercontent.com/898523/39407555-7455dbc6-4b7c-11e8-95da-8460b1ba2b69.png">

  - After
  <img width="20" alt="inverted-tray-after" src="https://user-images.githubusercontent.com/898523/39407554-744323c8-4b7c-11e8-96c8-fd0b2f367e9e.png">

- Launcher UI

  - Before
  <img width="606" alt="launcher-before" src="https://user-images.githubusercontent.com/898523/39407557-748ee9d4-4b7c-11e8-807a-396a304795c7.png">

  - After
  <img width="606" alt="launcher-after" src="https://user-images.githubusercontent.com/898523/39407556-747c459a-4b7c-11e8-8561-efe0f23635f5.png">

- Print Media
  - I think zazu currently has some hex stickers associated with it. 
  - Might be good to upload that template and see how the design could look in that format
  - Print media does not seem to be currently tracked through git and probably should be 

If anyone can think of a situation I have failed to recognize please add it to the list. 

[xcf-gimp-icon-template.zip](https://github.com/tinytacoteam/zazu/files/1958832/xcf-gimp-icon-template.zip)
^ Here are the template placeholders for the locations identified so far.

If you determine a new placement scenario that I did not think about and you are able to create an icon placeholder in xcf (gimp) format please attach it to a comment on this thread. 

I will work to place these templates in a repo or branch based on community feedback here.

**Comment by richardbmx** [comment]
Seeing what you have placed I can notice that the icon is incorporated very well in different presentations and small sizes, within the proposal I do I can incorporate different variations of color and size so that they can use it in whatever they want. As you can see, the Z is better identified than the pen and in addition to this is a more personal image that users can easily remember, the pen reminds me of ENCARTA encyclopedias :-)

If you need something more from me, do not hesitate to write me and I will annex it. I will work on the different variations and leave them here.

**Comment by richardbmx** [comment]
Design mock-up

![presentationnew](https://user-images.githubusercontent.com/35604837/39412395-bd46e2f4-4be9-11e8-8d55-227f07af2a53.png)
