### ISSUE TITLE
How can I add a folder for portable/local applications?

### ISSUE THREAD

**Issue by shaneknysh** [bayleeadamoss/zazu#323]
I have a folder of local portable utilities that are not installed but run directly from a folder. Zazu can't find these apps to launch them. I'd like to be able to add a path to Zazu that this folder also contains apps to launch

### Expected Behavior
Typing the name of a local or portable app will find the app in zazu and launch it.

### Actual Behavior
The app is not found.

### Versions

* Zazu:
App Environment: production
App Version: 0.5.2
Electron Version: 1.3.14
Node Version: 6.5.0
Chrome Version: 52.0.2743.82

* OS:
Windows 10 with latest windows update

* GIT:

**Comment by bayleedev** [comment]
There are instructions in the [zazu file finder docs](https://github.com/tinytacoteam/zazu-file-finder#installing)

**Comment by shaneknysh** [comment]
I've followed these instructions and the apps are not being indexed. Can I print out the appPath so I can test if the paths are added?

**Comment by shaneknysh** [comment]
I've found _a_ solution of sorts. 

I can't add folders like 
`C:\\Games`
I have to use relative addresses from 
`C:\Users\shaneknysh\.zazu\plugins\tinytacoteam\zazu-clipboard`

so this works
`..\\..\\..\\..\\..\\..\\Games`
