### ISSUE TITLE
Non-ideal ranking algorithm

### ISSUE THREAD

**Issue by amjith** [bayleeadamoss/zazu#47]
<img width="674" alt="1__0_2_vim_-__vim___users_amjith_dropbox_code_python_pgcli____tmux_" src="https://cloud.githubusercontent.com/assets/49260/17279773/1d6cb888-5732-11e6-8f17-0f88e2a0d834.png">

I would have assumed that "Terminal.app" would be higher in the list.

**Comment by bayleedev** [comment]
You're right, Terminal.app would be preferred as the default sort.

For a quick work around, if you have the latest version of Zazu and the lastest version of zazu-file-finder, you can click on the results and it will be ranked higher.

**Comment by bayleedev** [comment]
Fixed with tinytacoteam/zazu-file-finder@83ae381

Update your plugins via the menu item :D

**Comment by amjith** [comment]
Nice!! 
<img width="782" alt="1__0_2_node_-__npm___users_amjith_dropbox_code_javascript_zazu____tmux_" src="https://cloud.githubusercontent.com/assets/49260/17280569/27631df4-5747-11e6-929f-84b66d0a3aa8.png">
