### ISSUE TITLE
Add holiday to body class name

### ISSUE THREAD

**Issue by bayleedev** [bayleeadamoss/zazu#49]
This gives themes the ability to decorate based on holidays.

Here's a module I found that gives us the correct functionality:
https://gist.github.com/blainesch/b710aece2d679207340b6c8793817f6b

**Comment by singuerinc** [comment]
@blainesch not sure about it, shouldn't be a core functionality since it only adds the holiday class for US days, what about the rest of the World? I think a better idea could be a plugin like "zazu-us-holidays" or similar.

**Comment by bayleedev** [comment]
Very true about the us dates, I was considering just putting the date itself as a class, and themes can figure out what they want to do with it.
