### ISSUE TITLE
Provide a way to show items with LargeType like Alfred

### ISSUE THREAD

**Issue by amjith** [bayleeadamoss/zazu#76]
Select a text and type a shortcut to show the text in Large Type.

**Comment by bayleedev** [comment]
This could be accomplished by creating a [BrowserWindow](https://github.com/electron/electron/blob/master/docs/api/browser-window.md) and some way to fill a container with text. Maybe something [like this](http://jsfiddle.net/mn4rr/1/).

It appears the behavior in alfred is that the text will stay up until any interaction happens.
