### ISSUE TITLE
Some apps are not indexed by Zazu

### ISSUE THREAD

**Issue by amjith** [bayleeadamoss/zazu#85]
A few apps in my `/Applications` folder are not recognized by zazu and it is not listed in the results. One example is Visual Studio Code. 

<img width="824" alt="zazu_and_applications_and_inbox__15__-_amjith_r_gmail_com_-_gmail_ _and_1__0_0_fish_-__fish___users_amjith____tmux_" src="https://cloud.githubusercontent.com/assets/49260/21583636/a9875820-d03e-11e6-9a13-9697b97c93f9.png">

Log file attached: 

[zazu.log.2017-01-02.txt](https://github.com/tinytacoteam/zazu/files/680285/zazu.log.2017-01-02.txt)

**Comment by bayleedev** [comment]
This is a plugin issue, closing in favor of tinytacoteam/zazu-file-finder#5
