### ISSUE TITLE
PKGBuild for Arch?

### ISSUE THREAD

**Issue by harryio** [bayleeadamoss/zazu#91]

**Comment by bayleedev** [comment]
I'd love to get packages for this, there is currently a branch to switch to a new build system which will allow this to be much easier.

**Comment by bayleedev** [comment]
@harryio we've switched to a new build system which should make it easy to add additional release files. If you want to submit a pr that would be greatly appreciated. We just need travis to output the file :D

**Comment by harryio** [comment]
found it on arch as zazu-bin!
