### ISSUE TITLE
zazu is displaying on two screens at the same time

### ISSUE THREAD

**Issue by glc-mvion** [bayleeadamoss/zazu#92]
On Linux Mint with two Dell 24" screens (1920x1200) Zazu is displaying on the center of the two screens

![image](https://cloud.githubusercontent.com/assets/6715182/21634433/8f3ba168-d257-11e6-9ad3-83278271330e.png)

**Comment by bayleedev** [comment]
Thank you for reporting it [:

Also, the dark theme looks great with your desktop :D

**Comment by glc-mvion** [comment]
As i say often, 
> Dark theme or nothing !

**Comment by bayleedev** [comment]
@MattMattV also, you can drag Zazu to a better spot as a temporary workaround. It currently remembers where you left it.

**Comment by peterbrinck** [comment]
I'm running Ubuntu, and it only displays on my laptop screen (not split like @MattMattV ), even though it's not the default screen

**Comment by marcosnils** [comment]
This doesn't happen to me. It just opened in my main screen which is what I'd expect

**Comment by lendoly** [comment]
same problem here with Ubuntu and 2 monitors of 27" (1920x1080)

the workaround give by @blainesch works if I not restart the application or the pc

**Comment by eldinoyev** [comment]
hey @MattMattV and @lendoly, would you care to try my fork at https://github.com/eldinoyev/zazu and see if you still have the same problem? https://github.com/tinytacoteam/zazu/pull/169 should address it.

**Comment by bayleedev** [comment]
This is now merged into master if anybody here wants to test this. I'll update this ticket later once it's released.

**Comment by bayleedev** [comment]
This has been released, does anybody want to try testing this with v0.4.0?

**Comment by ghost** [comment]
For me it works: zazu comes up in the middle of my primary monitor

**Comment by glc-mvion** [comment]
It works well for me too !

**Comment by bayleedev** [comment]
Thanks!
