### ISSUE TITLE
zazu makes a beep on esc and enter

### ISSUE THREAD

**Issue by onsails** [bayleeadamoss/zazu#96]
I've installed zazu on osx 10.12.2, and it makes a beep sound each time I cancel zazu window or press enter. Is it common behavior? Is it configurable?

**Comment by bayleedev** [comment]
I would also like to turn it off, it's really annoying, but I guess I've gotten use to it. If you want to take a look, I'd greatly appreciate it! :D

**Comment by mvaneijgen** [comment]
Had the same issue and made a screencast showing the issue and than found this tread, so better to post it here than make a new tread. 

[![Screencast](https://img.youtube.com/vi/U2-8ILKd-Xw/0.jpg)](https://www.youtube.com/watch?v=U2-8ILKd-Xw&feature=youtu.be)

It sounds like the sound macOS makes when your doing something wrong.
