### ISSUE TITLE
Make a new page for themes only

### ISSUE THREAD

**Issue by singuerinc** [bayleeadamoss/zazu#98]
@blainesch What do you think about having a page (in the website) for themes?

Right now themes and plugins are in the same page but if the number of themes and plugins grow will be hard to keep track of each type.

I'm currently developing a theme: https://github.com/singuerinc/zazu-clean-dark-theme
But I would like to make more and display them somewhere.

Thanks!

**Comment by bayleedev** [comment]
Good idea, done! [:
